version: '3.8'
services:
    umerx_blackdog_trader_typescript:
        build:
            context: ./.devcontainer
            dockerfile: Dockerfile
        command: sleep infinity
        environment:
            - ALPACA_API_KEY=${ALPACA_API_KEY}
            - ALPACA_API_SECRET=${ALPACA_API_SECRET}
            - ALPACA_API_USE_TEST_CREDENTIALS=${ALPACA_API_USE_TEST_CREDENTIALS}
        volumes:
            - ./:/workspace
networks:
    default:
        external: true
        name: 'umerx_blackdog'
